name: Add latest tag to new release
on:
  release:
    types: [published, edited]

jobs:
  run:
    name: Add latest tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run latest-tag
        uses: EndBug/latest-tag@v1
